# Generated by Django 4.0.5 on 2022-07-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('review', models.TextField(max_length=3000)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
